# Feedback app redirects with resources explicitly handled
[[redirects]]
  from = "/feedback/style.css"
  to = "https://feedbackforgedt.netlify.app/style.css"
  status = 200
  force = true

[[redirects]]
  from = "/feedback/quality-input.css"
  to = "https://feedbackforgedt.netlify.app/quality-input.css"
  status = 200
  force = true

[[redirects]]
  from = "/feedback/feedback-generator.js"
  to = "https://feedbackforgedt.netlify.app/feedback-generator.js"
  status = 200
  force = true

[[redirects]]
  from = "/feedback"
  to = "https://feedbackforgedt.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "/feedback/*"
  to = "https://feedbackforgedt.netlify.app/:splat"
  status = 200
  force = true

# API redirects with force flag
[[redirects]]
  from = "/api/questions"
  to = "/.netlify/functions/fetch-questions"
  status = 200
  force = true

[[redirects]]
  from = "/api/categories"
  to = "/.netlify/functions/fetch-categories"
  status = 200
  force = true

# API routes from coaching subdirectory
[[redirects]]
  from = "/coaching/api/questions"
  to = "/.netlify/functions/fetch-questions"
  status = 200
  force = true

[[redirects]]
  from = "/coaching/api/categories"
  to = "/.netlify/functions/fetch-categories"
  status = 200
  force = true

# Coaching app subdirectory mapping
[[redirects]]
  from = "/coaching/*"
  to = "/:splat"
  status = 200

# Root redirect to coaching
[[redirects]]
  from = "/"
  to = "/coaching"
  status = 302

# SPA catch-all - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Caching and security headers
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800, stale-while-revalidate=86400"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800, stale-while-revalidate=86400"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"