[build]
  publish = "apps/coaching/public"
  functions = "apps/coaching/netlify/functions"

# First handle redirects to other apps
[[redirects]]
  from = "/feedback"
  to = "https://feedbackforgedt.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "/feedback/*"
  to = "https://feedbackforgedt.netlify.app/:splat"
  status = 200
  force = true

# API redirects with forceflag to ensure they take precedence
[[redirects]]
  from = "/api/questions"
  to = "/.netlify/functions/fetch-questions"
  status = 200
  force = true

[[redirects]]
  from = "/api/categories"
  to = "/.netlify/functions/fetch-categories"
  status = 200
  force = true

# Make sure API routes work from the subdirectory too
[[redirects]]
  from = "/coaching/api/questions"
  to = "/.netlify/functions/fetch-questions"
  status = 200
  force = true

[[redirects]]
  from = "/coaching/api/categories"
  to = "/.netlify/functions/fetch-categories"
  status = 200
  force = true

# Subdirectory redirects
[[redirects]]
  from = "/coaching/*"
  to = "/:splat"
  status = 200

# Ensure all routes go to index.html for client-side routing
# This must come LAST as it's the catch-all
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Moderate caching for static assets (7 days)
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800, stale-while-revalidate=86400"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800, stale-while-revalidate=86400"

# Cache HTML files for a short period
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"